name: SDK Type Check

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 6 * * 1-5' # weekly run
  workflow_dispatch:      # allow manual trigger

permissions:
  contents: read
  issues: write

jobs:
  typecheck-latest:
    uses: wormhole-foundation/workflows/.github/workflows/wormhole-demo-typecheck.yml@main
    secrets: inherit